name: Deploy Demo

on:
  workflow_run:
    workflows: [ 'CI' ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Connect to Tailnet
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test SSH
        run: ssh -o StrictHostKeyChecking=no root@concerto-fresh-demo "uname"